In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import re
import string

In [2]:
df_fake  = pd.read_csv('Fake - Fake.csv')
df_true = pd.read_csv('True.csv')

In [3]:
df_fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’s...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian C...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke ...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name ...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Duri...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [4]:
df_true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [5]:
df_fake['class'] = 0
df_true['class'] = 1

In [6]:
df_fake.shape, df_true.shape

((23481, 5), (21417, 5))

In [7]:
# Store last 10 fake rows
df_fake_manual_testing = df_fake.tail(10)
df_fake = df_fake.iloc[:-10]

# Store last 10 true rows
df_true_manual_testing = df_true.tail(10)
df_true = df_true.iloc[:-10]

In [8]:
df_fake.shape, df_true.shape

((23471, 5), (21407, 5))

In [9]:
df_fake_manual_testing['class'] = 0
df_true_manual_testing['class'] = 1

In [10]:
df_fake_manual_testing.head()

,title,text,subject,date,class
23471,Seven Iranians freed in the prisoner swap have...,"21st Century Wire says This week, the historic...",Middle-east,"January 20, 2016",0
23472,#Hashtag Hell & The Fake Left,By Dady Chery and Gilbert MercierAll writers ...,Middle-east,"January 19, 2016",0
23473,Astroturfing: Journalist Reveals Brainwashing ...,Vic Bishop Waking TimesOur reality is carefull...,Middle-east,"January 19, 2016",0
23474,The New American Century: An Era of Fraud,Paul Craig RobertsIn the last years of the 20t...,Middle-east,"January 19, 2016",0
23475,Hillary Clinton: ‘Israel First’ (and no peace ...,Robert Fantina CounterpunchAlthough the United...,Middle-east,"January 18, 2016",0

In [11]:
df_true_manual_testing.head()

,title,text,subject,date,class
21407,"Mata Pires, owner of embattled Brazil builder ...","SAO PAULO (Reuters) - Cesar Mata Pires, the ow...",worldnews,"August 22, 2017",1
21408,"U.S., North Korea clash at U.N. forum over nuc...",GENEVA (Reuters) - North Korea and the United ...,worldnews,"August 22, 2017",1
21409,"U.S., North Korea clash at U.N. arms forum on ...",GENEVA (Reuters) - North Korea and the United ...,worldnews,"August 22, 2017",1
21410,Headless torso could belong to submarine journ...,COPENHAGEN (Reuters) - Danish police said on T...,worldnews,"August 22, 2017",1
21411,North Korea shipments to Syria chemical arms a...,UNITED NATIONS (Reuters) - Two North Korean sh...,worldnews,"August 21, 2017",1

In [12]:
df_merge = pd.concat([df_fake, df_true], axis = 0)

In [13]:
df_merge.tail(10)

,title,text,subject,date,class
21397,Germany's Schulz says he would demand U.S. wit...,BERLIN (Reuters) - The leader of Germany s Soc...,worldnews,"August 23, 2017",1
21398,Blunt instrument? What a list of banned articl...,SHANGHAI (Reuters) - An old review of an acade...,worldnews,"August 23, 2017",1
21399,Saudi police release teenager detained for dan...,DUBAI (Reuters) - A 14-year-old boy who was de...,worldnews,"August 22, 2017",1
21400,"The People's Princess, Britons work to keep me...",LONDON (Reuters) - Abdul Daoud spilt most of t...,worldnews,"August 23, 2017",1
21401,"Argentina labor unions protest job losses, Mac...",BUENOS AIRES (Reuters) - Argentina s main labo...,worldnews,"August 22, 2017",1
21402,Exclusive: Trump's Afghan decision may increas...,ON BOARD A U.S. MILITARY AIRCRAFT (Reuters) - ...,worldnews,"August 22, 2017",1
21403,U.S. puts more pressure on Pakistan to help wi...,WASHINGTON (Reuters) - The United States sugge...,worldnews,"August 21, 2017",1
21404,Exclusive: U.S. to withhold up to $290 million...,WASHINGTON (Reuters) - The United States has d...,worldnews,"August 22, 2017",1
21405,Trump talks tough on Pakistan's 'terrorist' ha...,ISLAMABAD (Reuters) - Outlining a new strategy...,worldnews,"August 22, 2017",1
21406,"U.S., North Korea clash at U.N. forum over nuc...",GENEVA (Reuters) - North Korea and the United ...,worldnews,"August 22, 2017",1

In [14]:
df_merge.head()

,title,text,subject,date,class
0,Donald Trump Sends Out Embarrassing New Year’s...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian C...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke ...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name ...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Duri...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [15]:
df_merge.columns

Index(['title', 'text', 'subject', 'date', 'class'], dtype='object')

In [16]:
df = df_merge.drop(columns=['title', 'subject','date'], axis=1)

In [17]:
df.head()

                                                text  class
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0

In [18]:
df.shape

(44878, 2)

In [19]:
df.isnull().sum()

text     632
class      0
dtype: int64

In [20]:
df[df.isnull().any(axis=1)]

      text  class
10923  NaN      0
11041  NaN      0
11190  NaN      0
11225  NaN      0
11236  NaN      0
...    ...    ...
21827  NaN      0
21857  NaN      0
21873  NaN      0
22303  NaN      0
23086  NaN      0

[632 rows x 2 columns]

In [21]:
df = df.dropna()

In [22]:
df.shape

(44246, 2)

In [23]:
df.isnull().sum()

text     0
class    0
dtype: int64

In [24]:
# random shuffing
df = df.sample(frac =1)

In [25]:
df.head()

                                                    text  class
18704  COLBERT   LANGUAGE WARNING! This late night ho...      0
13458  WASHINGTON (Reuters) - U.S. Secretary of State...      1
7876   (Reuters) - Billionaire investor Warren Buffet...      1
7452   Mitt Romney watched his dream of becoming pres...      0
14575  Islamic terrorism is the #1 issue with most Am...      0

In [26]:
df.reset_index(inplace=True)
df.drop(columns =['index'], axis=1 , inplace=True)

In [27]:
df.head()

                                                text  class
0  COLBERT   LANGUAGE WARNING! This late night ho...      0
1  WASHINGTON (Reuters) - U.S. Secretary of State...      1
2  (Reuters) - Billionaire investor Warren Buffet...      1
3  Mitt Romney watched his dream of becoming pres...      0
4  Islamic terrorism is the #1 issue with most Am...      0

In [28]:
def text_preprocessing(text):
    text = str(text)
    text = text.lower()

    text = re.sub(r'\[.*?\]', '', text)

    # remove urls
    text = re.sub(r'https?://\S+|www\.\S+', '', text)

    # remove html
    text = re.sub(r'<.*?>+', '', text)

    # remove punctuation
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text)

    # remove newlines
    text = re.sub(r'\n', ' ', text)

    # remove words containing digits
    text = re.sub(r'\w*\d\w*', '', text)

    # remove special characters
    text = re.sub(r'\W', ' ', text)

    # remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [29]:
df['text'] = df['text'].apply(text_preprocessing)

In [30]:
X = df['text']
y = df['class']

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorization = TfidfVectorizer(
    ngram_range=(1,2),
    stop_words='english',
    max_df=0.7
)
x_train_vector = vectorization.fit_transform(X_train)
x_test_vector = vectorization.transform(X_test)

In [33]:
print(X_train.head())
print(X_train.shape)

32864    one of trump s latino surrogates marco gutierr...
30301    washington reuters democratic presidential can...
29333    moscow reuters the us house of representatives...
43319    istanbul reuters sixty people including a form...
27781    donald trump is counting on a big win tonight ...
Name: text, dtype: object
(35396,)

In [34]:
from sklearn.linear_model import LogisticRegression

lr =LogisticRegression()
lr.fit(x_train_vector,y_train)

LogisticRegression()

In [35]:
lr_pred = lr.predict(x_test_vector)

In [36]:
accuracy_score(y_test, lr_pred)

0.9832768361581921

In [37]:
print(classification_report(y_test, lr_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98      4638
           1       0.98      0.99      0.98      4212

    accuracy                           0.98      8850
   macro avg       0.98      0.98      0.98      8850
weighted avg       0.98      0.98      0.98      8850

In [38]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(x_train_vector, y_train)

DecisionTreeClassifier()

In [39]:
dt_pred = dt.predict(x_test_vector)

In [40]:
accuracy_score(y_test, dt_pred)

0.9961581920903955

In [41]:
print(classification_report(y_test, dt_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4638
           1       1.00      1.00      1.00      4212

    accuracy                           1.00      8850
   macro avg       1.00      1.00      1.00      8850
weighted avg       1.00      1.00      1.00      8850

In [43]:
# from sklearn.ensemble import GradientBoostingClassifier

# gbc = GradientBoostingClassifier(random_state=42)
# gbc.fit(x_train_vector,y_train)

KeyboardInterrupt:

In [ ]:
# gbc_pred = gbc.predict(x_test_vector)

In [ ]:
# accuracy_score(y_test, gbc_pred)

In [ ]:
# print(classification_report(y_test, gbc_pred))

In [45]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(random_state = 42,n_jobs=-1)
rfc.fit(x_train_vector, y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [46]:
rfc_pred = rfc.predict(x_test_vector)

In [47]:
accuracy_score(y_test, rfc_pred)

0.9821468926553673

In [48]:
print(classification_report(y_test, rfc_pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98      4638
           1       0.98      0.98      0.98      4212

    accuracy                           0.98      8850
   macro avg       0.98      0.98      0.98      8850
weighted avg       0.98      0.98      0.98      8850

In [49]:
def output_label(n):
    if n == 0:
        return "Fake News!!!"
    elif n == 1:
        return "Real News!!!"

def check_news(news):
    test_news = {"text": [news]}
    new_def_test = pd.DataFrame(test_news)
    new_def_test['text'] = new_def_test['text'].apply(text_preprocessing)
    new_x_test = new_def_test['text']
    new_x_test_vector = vectorization.transform(new_x_test)
    lr_pred = lr.predict(new_x_test_vector)
    dt_pred = dt.predict(new_x_test_vector)
    # gbc_pred = gbc.predict(new_x_test_vector)
    rfc_pred = rfc.predict(new_x_test_vector)

    return print("\n\nLR Prediction: {} \nDT Prediction: {}  \nRFC Prediction: {}".format(
        output_label(lr_pred[0]),
        output_label(dt_pred[0]),
        output_label(rfc_pred[0])
    ))

In [50]:
news = str(input())
check_news(news)

 India Successfully Lands Chandrayaan-3 Near the Moon’s South Pole  India’s space agency, ISRO, successfully landed the Chandrayaan-3 spacecraft near the Moon’s south polar region on August 23, 2023. With this achievement, India became the fourth country to achieve a soft landing on the Moon and the first to land near the lunar south pole.  The mission’s Vikram lander and Pragyan rover were designed to conduct scientific experiments and study the lunar surface. The achievement was widely celebrated internationally and confirmed by multiple global news organizations and official ISRO broadcasts.

LR Prediction: Real News!!!
DT Prediction: Fake News!!!
RFC Prediction: Real News!!!

In [52]:
news = str(input())
check_news(news)

 🚨 BREAKING: Scientists Discover Chocolate Can Completely Cure Diabetes Overnight  A group of unnamed researchers allegedly discovered that eating two bars of dark chocolate every night can permanently cure diabetes within 24 hours. Social media users claim pharmaceutical companies are trying to suppress the information to protect profits.  Experts supposedly involved in the “study” say the treatment works for all age groups and requires no medical supervision. However, no verified medical journal or health organization has confirmed these claims.

LR Prediction: Fake News!!!
DT Prediction: Fake News!!!
RFC Prediction: Fake News!!!